#!/usr/bin/env python3
"""
Stage 2 Impact Report Validator (PIPE-E2-003)

Deterministic validation that enforces product-aware quality rules on
impact reports generated by Stage 2.

Validation rules:
  1. Schema completeness (required keys)
  2. Engines affected threshold (>= 2)
  3. Compound score threshold (>= 0.3)
  4. Compound score recomputation verification
  5. Engine existence in engine_graph.json
  6. Propagation path validity (edges exist in graph)
  7. Consistency (len(affected_engines) == engines_affected)
  8. Recommendation coherence (PROCEED/REJECT matches thresholds)
  9. Contract reference validation (optional)

Usage:
    python3 scripts/validate_impact_report.py \
        --report impact_report_tv-001.json \
        --config config/thresholds.json \
        --engine-graph config/engine_graph.json \
        [--contracts contracts.json] \
        --output validation_stage2_tv-001.json
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone


REQUIRED_KEYS = [
    "finding_id",
    "engines_affected",
    "compound_score",
    "propagation_paths",
    "affected_engines",
    "scoring_breakdown",
    "recommendation",
    "rationale",
]

SCORING_DIMENSIONS = [
    "engines_affected",
    "propagation_depth",
    "contract_impact",
    "test_coverage_delta",
]


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------

def load_json(path):
    """Load JSON file. Exit 1 on failure."""
    try:
        with open(path, "r") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"ERROR: Cannot load {path}: {e}", file=sys.stderr)
        sys.exit(1)


def load_config(config_path):
    """Load stage_2 thresholds from config."""
    if not config_path or not os.path.isfile(config_path):
        return 0.3, 2
    config = load_json(config_path)
    stage_2 = config.get("stage_2", {})
    return (
        stage_2.get("compound_score_minimum", 0.3),
        stage_2.get("engines_affected_minimum", 2),
    )


# ---------------------------------------------------------------------------
# Validation checks
# ---------------------------------------------------------------------------

def check_schema(report):
    """Rule 1: Required keys present."""
    missing = [k for k in REQUIRED_KEYS if k not in report]
    if missing:
        return {"check": "schema_completeness", "result": "FAIL",
                "reason": f"Missing keys: {', '.join(missing)}"}
    return {"check": "schema_completeness", "result": "PASS"}


def check_engines_threshold(report, minimum):
    """Rule 2: engines_affected >= minimum."""
    count = report.get("engines_affected", 0)
    if count < minimum:
        return {"check": "engines_affected_threshold", "result": "FAIL",
                "reason": f"engines_affected={count} below threshold {minimum}"}
    return {"check": "engines_affected_threshold", "result": "PASS"}


def check_compound_score_threshold(report, minimum):
    """Rule 3: compound_score >= minimum."""
    score = report.get("compound_score", 0.0)
    if score < minimum:
        return {"check": "compound_score_threshold", "result": "FAIL",
                "reason": f"compound_score={score} below threshold {minimum}"}
    return {"check": "compound_score_threshold", "result": "PASS"}


def check_score_verification(report):
    """Rule 4: Recompute compound_score from scoring_breakdown."""
    breakdown = report.get("scoring_breakdown", {})
    declared = report.get("compound_score", 0.0)

    expected = 0.0
    for dim in SCORING_DIMENSIONS:
        dim_data = breakdown.get(dim, {})
        value = dim_data.get("value", 0.0)
        weight = dim_data.get("weight", 0.0)
        expected += value * weight

    if abs(expected - declared) >= 0.01:
        return {"check": "score_verification", "result": "FAIL",
                "reason": f"Declared score {declared} != computed {round(expected, 4)} (from breakdown)"}
    return {"check": "score_verification", "result": "PASS"}


def check_engine_existence(report, engine_graph):
    """Rule 5: All affected_engines exist in engine_graph."""
    graph_engines = set(engine_graph.get("engines", {}).keys())
    affected = report.get("affected_engines", [])
    unknown = [e for e in affected if e not in graph_engines]
    if unknown:
        return {"check": "engine_existence", "result": "FAIL",
                "reason": f"Unknown engines: {', '.join(unknown)}"}
    return {"check": "engine_existence", "result": "PASS"}


def check_propagation_paths(report, engine_graph):
    """Rule 6: Propagation paths follow actual graph edges."""
    paths = report.get("propagation_paths", [])
    engines = engine_graph.get("engines", {})
    invalid = []

    for path in paths:
        from_engine = path.get("from", "")
        to_engine = path.get("to", "")

        # Both must exist
        if from_engine not in engines or to_engine not in engines:
            invalid.append(f"{from_engine}->{to_engine} (engine not in graph)")
            continue

        # to must be in feeds or depended_by of from
        from_data = engines.get(from_engine, {})
        reachable = set(from_data.get("feeds", []) + from_data.get("depended_by", []))
        if to_engine not in reachable:
            invalid.append(f"{from_engine}->{to_engine} (no edge in graph)")

    if invalid:
        return {"check": "propagation_path_validity", "result": "FAIL",
                "reason": f"Invalid paths: {'; '.join(invalid)}"}
    return {"check": "propagation_path_validity", "result": "PASS"}


def check_consistency(report):
    """Rule 7: len(affected_engines) == engines_affected."""
    affected = report.get("affected_engines", [])
    declared = report.get("engines_affected", 0)
    if len(affected) != declared:
        return {"check": "consistency", "result": "FAIL",
                "reason": f"affected_engines has {len(affected)} items but engines_affected={declared}"}
    return {"check": "consistency", "result": "PASS"}


def check_recommendation_coherence(report, score_min, engines_min):
    """Rule 8: Recommendation must match threshold logic."""
    engines = report.get("engines_affected", 0)
    score = report.get("compound_score", 0.0)
    rec = report.get("recommendation", "").upper()

    should_proceed = engines >= engines_min and score >= score_min

    if should_proceed and rec != "PROCEED":
        return {"check": "recommendation_coherence", "result": "FAIL",
                "reason": f"Should be PROCEED (engines={engines}>={engines_min}, score={score}>={score_min}) but got {rec}"}
    if not should_proceed and rec == "PROCEED":
        return {"check": "recommendation_coherence", "result": "FAIL",
                "reason": f"Should be REJECT (engines={engines}, score={score}) but got PROCEED"}
    return {"check": "recommendation_coherence", "result": "PASS"}


def check_contract_references(report, contracts):
    """Rule 9: Contract references point to real protocols."""
    if not contracts:
        return {"check": "contract_reference_validation", "result": "SKIP",
                "reason": "No contracts provided"}

    # If no protocols were extracted at all, the language likely lacks
    # contract extraction support — skip rather than fail.
    engines_data = contracts.get("engines", {})
    total_protocols = sum(
        len(e.get("protocols", [])) + len(e.get("ports", []))
        for e in engines_data.values()
    )
    if total_protocols == 0:
        return {"check": "contract_reference_validation", "result": "SKIP",
                "reason": "No protocols extracted (language may lack contract parser)"}

    breakdown = report.get("scoring_breakdown", {})
    contract_impact = breakdown.get("contract_impact", {}).get("value", 0.0)
    if contract_impact <= 0.0:
        return {"check": "contract_reference_validation", "result": "PASS"}

    # Check that at least one affected engine has protocols in contracts
    affected = report.get("affected_engines", [])
    has_protocols = False
    for engine in affected:
        engine_contracts = engines_data.get(engine, {})
        ports = engine_contracts.get("ports", [])
        protocols = engine_contracts.get("protocols", [])
        if ports or protocols:
            has_protocols = True
            break

    if not has_protocols:
        return {"check": "contract_reference_validation", "result": "FAIL",
                "reason": "contract_impact > 0 but no affected engine has protocols in contracts"}
    return {"check": "contract_reference_validation", "result": "PASS"}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def validate(report, config_path, engine_graph, contracts=None):
    """Run all validation checks. Returns (result, checks)."""
    score_min, engines_min = load_config(config_path)

    checks = [
        check_schema(report),
        check_engines_threshold(report, engines_min),
        check_compound_score_threshold(report, score_min),
        check_score_verification(report),
        check_engine_existence(report, engine_graph),
        check_propagation_paths(report, engine_graph),
        check_consistency(report),
        check_recommendation_coherence(report, score_min, engines_min),
        check_contract_references(report, contracts),
    ]

    failures = [c for c in checks if c["result"] == "FAIL"]
    result = "REJECTED" if failures else "ACCEPTED"

    return result, checks


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Validate Stage 2 impact report against product constraints"
    )
    parser.add_argument(
        "--report", required=True,
        help="Path to impact report JSON"
    )
    parser.add_argument(
        "--config", default=None,
        help="Path to thresholds.json"
    )
    parser.add_argument(
        "--engine-graph", required=True,
        help="Path to engine_graph.json"
    )
    parser.add_argument(
        "--contracts", default=None,
        help="Path to contracts.json (optional)"
    )
    parser.add_argument(
        "--output", required=True,
        help="Path to write validation result JSON"
    )
    args = parser.parse_args(argv)

    report = load_json(args.report)
    engine_graph = load_json(args.engine_graph)
    contracts = load_json(args.contracts) if args.contracts else None

    result, checks = validate(report, args.config, engine_graph, contracts)

    output = {
        "stage": "validate_impact_report",
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "finding_id": report.get("finding_id", "unknown"),
        "result": result,
        "checks": checks,
    }

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as f:
        json.dump(output, f, indent=2)
        f.write("\n")

    print(json.dumps({
        "stage": "validate_impact_report",
        "finding_id": report.get("finding_id", "unknown"),
        "result": result,
        "checks_passed": sum(1 for c in checks if c["result"] == "PASS"),
        "checks_failed": sum(1 for c in checks if c["result"] == "FAIL"),
        "status": "complete",
    }))

    if result == "REJECTED":
        sys.exit(1)


if __name__ == "__main__":
    main()
